name: Push File

on:
  push:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git identity
        run: |
          git config --global user.email "eng21ct0044@dsu.edu.in"
          git config --global user.name "Tanya-DSU"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bandit
        run: |
          pip install bandit
          bandit -r .
  wapiti_scan:
    runs-on: ubuntu-latest
    needs: bandit_scan
    steps:
      - name: Install Wapiti
        run: |
          sudo apt-get -y install wapiti
          wapiti -u https://ODOP.streamlit.app/
  selenium_test:
    runs-on: ubuntu-latest
    needs: [bandit_scan, wapiti_scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0  # Replace with your Python version
      - name: Install Dependencies
        run: |
         pip install selenium
  # Add any other necessary dependencies with "pip install" as we
      - name: Run Selenium Tests
        run: python try.py
          
  copy-file:
    runs-on: ubuntu-latest
    needs: [bandit_scan, wapiti_scan,selenium_test]
    permissions:
      contents: write
      packages: write
      pages: write 
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Push a file to another repository
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
       API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN_1 }} # Use the correct environment variable name
      with:
        source_file: 'python.py'
        destination_repo: 'ODOP-Test'
        user_email: 'eng21ct0044@dsu.edu.in'
        user_name: 'Tanya-DSU'
        commit_message: 'success'
