name: Push File

on:
  push:
    branches:
      - main

jobs:
  
  copy-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write 
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: client
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
       API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN_1}} # Use the correct environment variable name
      with:
        source_file: 'client'
        destination_repo: 'One-District-One-Product/ODOP-Test'
        user_email: 'eng21ct0044@dsu.edu.in'
        user_name: 'Tanya-DSU'
        
    
